/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define SCB_CPACR (*(volatile unsigned int*)0xE000ED88)

void FPU_Enable(void) {
    SCB_CPACR |= ((3UL << 20) | (3UL << 22));
}
void delay(volatile uint32_t count){
	while(count--);
}

int main(void)
{
   FPU_Enable();

   //AHB1ENR'nin GPIOA portuna açılan registerının adresi pointer olarak atanır.
   volatile uint32_t *RCC_AHB1ENR = (volatile uint32_t*)0x40023830;


   *RCC_AHB1ENR |= (1<<0);//0X40023830'daki GPIOA portunun clock'u açılır.
   *RCC_AHB1ENR |= (1<<3);//0X40023830'daki GPIOD portunun clock'u açılır.

   volatile uint32_t *GPIOA_MODER = (volatile uint32_t*)0x40020000;
   volatile uint32_t *GPIOD_MODER = (volatile uint32_t*)0x40020C00;

   *GPIOA_MODER &= ~(3<<0); //MODER'ın ilk iki biti temizlenir.
   *GPIOA_MODER |= (0<<0);//MODER'ın ilk iki biti 0 yapılır.

   *GPIOD_MODER &= ~(3<<(12*2));//MODER'ın 24. ve 25. bitleri temizlenir.(PD12 için)
   *GPIOD_MODER |= (1<<(12*2));//MODER'ın 24.biti 1 ve 25. biti 0 yapılır.
   volatile uint32_t *GPIOA_IDR = (volatile uint32_t*)0x40020010;
   volatile uint32_t *GPIOD_ODR = (volatile uint32_t*)0x40020C14;

   while(1){

	   //IDR 1 (butona basılıyorsa)ise LEDi yak.
	   if(*GPIOA_IDR & (1<<0)){
		  *GPIOD_ODR |= (1<<12);
	   }else{
		   *GPIOD_ODR &= ~(1<<12);
	   }

   }
}
