/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define SCB_CPACR (*(volatile unsigned int*)0xE000ED88)

void FPU_Enable(void) {
    SCB_CPACR |= ((3UL << 20) | (3UL << 22));
}

void EXTI0_IRQHandler(void) {


	volatile uint32_t *GPIOD_ODR = (volatile uint32_t*)0x40020C14;
	*GPIOD_ODR ^= (1<<15);

	volatile uint32_t *EXTI_PR = (volatile uint32_t*)0x40013C14;
	*EXTI_PR |= (1<<0);
}

void Blink_LED(void){
	volatile uint32_t *RCC_AHB1ENR = (volatile uint32_t*)0x40023830;
	*RCC_AHB1ENR |= (1<<3) | (1<<0);
	volatile uint32_t *GPIOD_MODER = (volatile uint32_t*)0x40020C00;
	*GPIOD_MODER &= ~(3<<(15*2));
	*GPIOD_MODER |= (1<<(15*2));
}
int main(void)
{

	FPU_Enable();

	//SYSCFG register'ı için APB2ENR bus'ının RCC'si pointer olarak tanımlandı.
	volatile uint32_t *RCC_APB2ENR = (volatile uint32_t*)0x40013844;

	//RCC pointerının ilgili register (SYSCFG) için 14. bitte olduğundan, ilgili bit set edildi.
	*RCC_APB2ENR |= (1<<14);

	//User Button PA0 pinine denk gelmektedir. PA0 için ilgili peripheral EXTI0'dır.
	//EXTI0 da SYSCFG_EXTICR1 register'ına denk gelmektedir.

	//SYSCFG_EXTICR1 register'ı pointer olarak tanımlandı.
	volatile uint32_t *SYSCFG_EXTICR1 = (volatile uint32_t*)0x40013808;

	//4 bitin önceden her ihtimale karşı temizlenmesi için 1111(0xF) değeri kullanıldı.
	//PA0 pinine EXTI0'ı bağlamak için halihazırda 0000 yapmak gerektiğinden sadece temizleme işlemi yeterli.
	*SYSCFG_EXTICR1 &= ~(0xF<<0);

	//EXTI_IMR (ilgili kesmelere duyarlı olmak için) register'ı pointer olarak tanımlandı.
	volatile uint32_t *EXTI_IMR = (volatile uint32_t*)0x40013C00;

	//1 yapıldığı takdirde hattı dinlemeye başlayacaktır.
	*EXTI_IMR |= (1<<0);

	//STM32F407'de user button pull_down'dur.(Yani butona basınca değer 1 olur)
	//Bu yüzden EXTI_RTSR register'ı (0V--> 3.3V) pointer olarak tanımlandı.
	volatile uint32_t *EXTI_RTSR = (volatile uint32_t*)0x40013C08;

	//Aktif edildi.
	*EXTI_RTSR |= (1<<0);

	//NVIC_ISER register'ı kesmeye CPU tarafından işlenmesine izin verilip verilmeyeceğini kontrol etmeye yarar.
	//NVIC_ISER'in adresi Cortex-M4 programlama kılavuzundan bakılmalı, reference-manuel'den değil.
	volatile uint32_t *NVIC_ISER0 = (volatile uint32_t*)0xE000E100;

	//6 numaralı IRQ'ye (kesme talebinin ID'si) izin verildi.
	*NVIC_ISER0 |= (1<<6);

	Blink_LED();

	while(1){
		//Sonsuz döngüde burada kal.
	}
	return 0;
}
